### ISSUE TITLE
add model weights

### ISSUE THREAD

**Issue by fabricecarles** [zju3dv/EfficientLoFTR#2]
When do you plan to provide the model weights?
I would like to use them to do a comparative benchmark in our study
best regards

**Comment by wyf2020** [comment]
Thank you for your interest in our work. We plan to release our code and model weights next week.

**Comment by wyf2020** [comment]
We have released the inference code and model weights! Some code to optimize performance will be released next.

**Comment by AbhiKhoyani** [comment]
May I know from where I can find weights `.ckpt` files? I'm planning to add this models in kornia library so!
