### ISSUE TITLE
image size for training and Ablation Studies of Image Resolution

### ISSUE THREAD

**Issue by guanfang12** [zju3dv/EfficientLoFTR#26]
What image size is used for training? This may not be mentioned in paper.
As for table 8 (Impact of test image resolution on the MegaDepth dataset), do you use the corresponding resolution for training and evaluation or use the same model for different evaluation resolution?

**Comment by wyf2020** [comment]
Hi,

Thank you for your question. All experiments in our paper use the same model trained at 832*832 on the MegaDepth datasets.

**Comment by guanfang12** [comment]
Do you have any test results of training at a higher resolution, for example, using a model trained with a megadepth of 1152*1152 for testing?

**Comment by wyf2020** [comment]
Sorry, we don't have relevant test results, but I think it's an interesting thing to be explored.

**Comment by guanfang12** [comment]
Thanks for your reply～
