### ISSUE TITLE
开源了吗

### ISSUE THREAD

**Issue by jxhoh** [zju3dv/EfficientLoFTR#3]

**Comment by jxhoh** [comment]
开源了吗

**Comment by jxhoh** [comment]
太吊了作者

**Comment by jxhoh** [comment]
> 感谢对我们工作的支持与关注。我们的代码预计下周开源。

作者到时候会开源训练代码吗，我想用你们的代码试试遥感数据的训练和测试，不知道可行不可行，看上一篇loftr ，我可以使用遥感影像的左片和右片，然后根据dem 或者dsm ，做一个训练？，让这个模型在遥感上也能得到应用？

**Comment by wyf2020** [comment]
我们的测试代码已经开源，训练代码正在整理，即将开源。非常欢迎在各种数据集上训练和尝试我们的模型！

**Comment by jxhoh** [comment]
> 我们的测试代码已经开源，训练代码正在整理，即将开源。非常欢迎在各种数据集上训练和尝试我们的模型！

![image](https://github.com/zju3dv/EfficientLoFTR/assets/100210383/81bc2374-861f-4a22-a7b9-7203bd9de4c1)
我想要跟上一个版本一样，这样使用呢，作者这个需要自己写代码吗

**Comment by jxhoh** [comment]
> 我们的测试代码已经开源，训练代码正在整理，即将开源。非常欢迎在各种数据集上训练和尝试我们的模型！

好像是没有看见这个matcher

**Comment by jxhoh** [comment]
不好意思，我翻阅了代码，我的错，我以为里面的代码跟loftr是一样的，haha，没想到里面更改来了
