### ISSUE TITLE
x_mask and source_mask is None

### ISSUE THREAD

**Issue by spacycoder** [zju3dv/EfficientLoFTR#32]
Hi, great work!

Quick question, why do you assert that x_mask and source_mask should be `None` here:

https://github.com/zju3dv/EfficientLoFTR/blob/68eb9218c1bdd179db9a07ad4771161b198d98b3/src/loftr/loftr_module/transformer.py#L65

Shouldn't the masks be applied to the qkv tensors? The rest of the code seems to allow for x_mask and source_mask to be available

**Comment by wyf2020** [comment]
Thank you for your question! Currently, our code only support padding mask and will crop image by padding mask before transformer. If you want to use mask of generalized shape, you can pass the mask into [here](https://github.com/zju3dv/EfficientLoFTR/blob/68eb9218c1bdd179db9a07ad4771161b198d98b3/src/loftr/loftr_module/linear_attention.py#L69) and modify the parameter of F.scaled_dot_product_attention or add a manually mask like [LoFTR](https://github.com/zju3dv/LoFTR/blob/df7ca80f917334b94cfbe32cc2901e09a80e70a8/src/loftr/loftr_module/linear_attention.py#L70). We will provide config choice for this operation soon. For more detailed explanation, you can also have a look at this [issue](https://github.com/zju3dv/EfficientLoFTR/issues/6).

**Comment by spacycoder** [comment]
OK, thanks!
