### ISSUE TITLE
请问训练数据还是沿用了LoFTR的设置吗？

### ISSUE THREAD

**Issue by Zoomds** [zju3dv/EfficientLoFTR#37]
你好，祝贺你的出色工作！D2-Net preprocessed images已经失效，我找了好久没找到，如果你们还使用这个的话，能否发我一份？感激不尽！

**Comment by wyf2020** [comment]
你好，我们使用了和LoFTR相同的训练数据和设置，但是可能由于MegaDepth数据集潜在的license问题，我们无法提供images，你可以先下载[MegaDepth数据集](https://github.com/mihaidusmanu/d2-net/issues/93#issuecomment-1211805143)，再使用[D2-Net代码](https://github.com/mihaidusmanu/d2-net/issues/93#issuecomment-1211805143)处理图像。

**Comment by Zoomds** [comment]
好的，感谢快速回复。
