### ISSUE TITLE
有个疑问想请教下~~~

### ISSUE THREAD

**Issue by andynnnnn** [zju3dv/EfficientLoFTR#39]
LoFTR是输入两张图像，如果我一张图像是针对某个目标的局部小场景特写照片，另外一张图是包含该目标的周围环境的大场景照片；类似于这两张图像的输入，LoFTR算法能完成的很好吗？请问是否有做过类似的测试

**Comment by wyf2020** [comment]
你好，这种情况属于图像匹配中常见的scale变换问题，EfficientLoFTR没有针对scale变换做特殊设计，但一般的scale变换都能解决，你可以使用OETR划分的[scale变化数据集](https://github.com/TencentYoutuResearch/ImageMatching-OETR)测试各种匹配方法在scale变换数据的表现。

**Comment by andynnnnn** [comment]
好的，谢谢！

**Comment by szyfh** [comment]
> 你好，这种情况属于图像匹配中常见的scale变换问题，EfficientLoFTR没有针对scale变换做特殊设计，但一般的scale变换都能解决，你可以使用OETR划分的[scale变化数据集](https://github.com/TencentYoutuResearch/ImageMatching-OETR)测试各种匹配方法在scale变换数据的表现。

您好，麻烦请教一下这种scale变换的问题有哪篇文章具体讲了解决办法吗？

**Comment by wyf2020** [comment]
> > 你好，这种情况属于图像匹配中常见的scale变换问题，EfficientLoFTR没有针对scale变换做特殊设计，但一般的scale变换都能解决，你可以使用OETR划分的[scale变化数据集](https://github.com/TencentYoutuResearch/ImageMatching-OETR)测试各种匹配方法在scale变换数据的表现。
> 
> 您好，麻烦请教一下这种scale变换的问题有哪篇文章具体讲了解决办法吗？

你好，可以参考[这个仓库](https://github.com/chicleee/Image-Matching-Paper-List)里整理的论文。

**Comment by szyfh** [comment]
好的谢谢！
