### ISSUE TITLE
在训练中出现 no gt fine match found for local regress

### ISSUE THREAD

**Issue by RunyuZhu** [zju3dv/EfficientLoFTR#50]
感谢您团队优秀的工作！
我想向您咨询我在复现训练回结果的过程中遇到的问题：
所有的数据准备是按照loftr的训练准备做的。所有参数使用的是您文件中的默认，但eloftr代码在val阶段会提示出，没有fine match的gt值。
我想知道可能是哪里的问题？
希望得到您的回复！

**Comment by RunyuZhu** [comment]
我定位到coarse matching 模块中的sim_matrix在经过阈值筛选后的结果全部为False，没有任何两个点间的相似度高于0.1。
希望得到您进一步的回复！

**Comment by wyf2020** [comment]
你好，这个warning只要不是每个iteration都会出现，在训练里偶尔出现是正常现象。
